# Generated by Django 3.2.10 on 2023-05-09 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoDeViagemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeTransporteModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeSolicitacaoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeViagemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ViagemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_passagem', models.CharField(max_length=200)),
                ('dada_inicio', models.DateTimeField()),
                ('dada_fim', models.DateField()),
                ('origem', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('objetivo', models.CharField(max_length=200)),
                ('autorizada', models.BooleanField(default=False)),
                ('homologada', models.BooleanField(default=False)),
                ('pagamento', models.CharField(blank=True, choices=[('RECURSOS DA EMPRESA', 'RECURSOS DA EMPRESA'), ('RECURSOS PRÓPRIOS', 'RECURSOS PRÓPRIOS')], max_length=50, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('dada_inicio_realizada', models.DateTimeField(blank=True, null=True)),
                ('dada_fim_realizada', models.DateField(blank=True, null=True)),
                ('remarcacao_interesse_particular', models.CharField(choices=[('1', 'SIM'), ('0', 'NAO')], default=0, max_length=50)),
                ('finalizar_pc', models.CharField(blank=True, choices=[('1', 'SIM'), ('0', 'NAO')], default='0', max_length=50, null=True)),
                ('aprovar_pc', models.CharField(blank=True, choices=[('2', 'REPROVADO'), ('1', 'APROVADO'), ('0', 'EM ANÁLISE')], default='0', max_length=50, null=True)),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagem_motivo', to='viagem.motivodeviagemmodel')),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viagem_user', to=settings.AUTH_USER_MODEL)),
                ('tipo_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagem_solicitacao', to='viagem.tiposdeviagemmodel')),
                ('tipo_transporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagem_transporte', to='viagem.tipodetransportemodel')),
                ('tipo_viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagem_tipo', to='viagem.tiposdeviagemmodel')),
            ],
            options={
                'verbose_name': 'Viagens',
                'permissions': (('solicitar_viagens', 'Pode solicitar viagens'), ('autorizar_viagens', 'Pode autorizar viagens'), ('homologar_viagens', 'Pode homologar viagens'), ('cadastrar_item_viagens', 'Cadastrar Items de Viagem')),
            },
        ),
        migrations.CreateModel(
            name='Arquivos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('file', models.FileField(upload_to='files/')),
                ('viagem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_viagem', to='viagem.viagemmodel')),
            ],
        ),
    ]
