# Generated by Django 3.2.10 on 2023-04-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horassemanais',
            name='aprovada',
        ),
        migrations.RemoveField(
            model_name='horassemanais',
            name='reprovada',
        ),
        migrations.RemoveField(
            model_name='horassemanais',
            name='submetida',
        ),
        migrations.AddField(
            model_name='horassemanais',
            name='situacao',
            field=models.IntegerField(default=0),
        ),
    ]
