# Generated by Django 3.2.10 on 2023-05-09 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0002_auto_20230424_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horassemanais',
            name='hr_seg',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='horassemanais',
            name='semanas',
            field=models.CharField(choices=[('30/04/2023 - 06/05/2023', '30/04/2023 - 06/05/2023'), ('07/05/2023 - 13/05/2023', '07/05/2023 - 13/05/2023'), ('14/05/2023 - 20/05/2023', '14/05/2023 - 20/05/2023'), ('21/05/2023 - 27/05/2023', '21/05/2023 - 27/05/2023'), ('28/05/2023 - 03/06/2023', '28/05/2023 - 03/06/2023')], max_length=200),
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('valor', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='files/')),
                ('situacao', models.CharField(blank=True, choices=[('3', 'REPROVADA'), ('2', 'APROVADA'), ('1', 'SUBMETIDA'), ('0', 'NÃO SUBMETIDA')], default='0', max_length=1, null=True)),
                ('solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastos_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
